---
  - name: base system configuration for linux server
    hosts: prod
    become: true
    tasks:
      - name: create admin user
        user:
            name: admin
            state: present
            uid: 5001
      - name: remove user dojo if presnt
        user:
          name: dojo
          state: absent
      - name: install tree
        yum:
          name: tree
          state: present
      - name: install ntp
        yum:
          name: ntp
          state: installed
      - name: start service ntp
        service:
          name: ntp
          state: started
